FROM node:19 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
RUN npm cache clean --force && npm run build --verbose

FROM node:19-alpine

WORKDIR /app

COPY --from=build /app .

EXPOSE 3000

CMD ["npm","start"]