FROM node:19-alpine AS builder

WORKDIR /listener

COPY package.json package-lock.json ./

RUN npm install --only=production

COPY . .

FROM node:19-alpine AS production


WORKDIR /listener

COPY --from=builder /listener .

EXPOSE 1001  

CMD ["npm", "run", "listener"]
