
FROM node:19 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
RUN npm run build
FROM node:19-alpine

WORKDIR /app

COPY --from=build /app .


EXPOSE 5000

CMD ["npm", "run","dlq"]