apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  accessKeyId: <YOUR_AWS_ACCESS_KEY_ID>
  secretAccessKey: <YOUR_AWS_SECRET_ACCESS_KEY_ID>

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-secret: YW1zcTkzNjc=

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET_KEY: PHlvdXItand0LXNlY3JldD4=
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:
  USER_PASSWORD: <YOUR_EMAIL_PASSWORD>
