apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  accessKeyId: QUtJQVlFS1A1TExZUTdBSERZT0o=
  secretAccessKey: UXU0dU9ZTU5xZUZUTjFoTUJCS2FQMHhjNXE2c2tnelhSYVpiTWRXNg==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-secret: YW1zcTkzNjc=
